Attila dashboard
greenfox-zerda-lasers/konnekt-frontend pull request #14
Opened 2017-02-09 10:58 UTC by h-attila

some dashboard design added...

2017-02-11 15:07 UTC, hubudibu requested changes
+ remove both `newcontact` images, use a button tag with real text instead, + an svg icon for the + sign

2017-02-11 15:07 UTC, hubudibu commented on web/dashboard.html
> +        <div class="table-header">
if it's a table, try using a `table` element!

2017-02-11 15:07 UTC, hubudibu commented on web/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Raleway:400,800" rel="stylesheet">
you can import multiple fonts in one link tag from google fonts and thus reduce the number of requests: `https://fonts.googleapis.com/css?family=Merriweather:400i|Raleway:400,800`

2017-02-11 15:07 UTC, hubudibu commented on web/dashboard.html
> +  <div class="dashboard-container">
use a `table` element for tabled data

2017-02-11 15:07 UTC, hubudibu commented on web/src/app.js
> +konnektApp.factory('DataHandling', ['HttpService', function (HttpService) {
what kind of data? as I see it's all about contacts, let's call it something like that. data is way too broad

2017-02-13 21:59 UTC, h-attila commented
conflicts resolved

2017-02-13 22:02 UTC, h-attila commented on web/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Raleway:400,800" rel="stylesheet">
cool! :)

2017-02-13 22:34 UTC, merged