organizing scss
greenfox-zerda-lasers/konnekt-frontend pull request #21
Opened 2017-02-14 15:10 UTC by h-attila

2017-02-19 21:08 UTC, hubudibu requested changes

2017-02-19 21:08 UTC, hubudibu commented on web/dashboard.html
> +      <div class="dashboard table-header-container">
`<table> pls`

2017-02-19 21:08 UTC, hubudibu commented on web/dashboard.html
> +      <div class="table-header-text-container">
use a table element for tabled data

2017-02-19 21:08 UTC, hubudibu commented on web/src/css/_dashboard.scss
> +        .table-header-text {
avoid unnecessary nesting in sass - this will compile to `.table-header-container .table-header  .table-header-text-container .table-header-text`, and will be a pain to overwrite.

are you sure this is the shortest selector that can do the job? is every display value described here is that value because that text is in the text-container in the header in the header-container, or just because it's a table header?

2017-02-19 21:08 UTC, hubudibu commented on web/src/css/main.scss
> +@external _popup.scss;
what's `@external`?
`@import` would be the way to include scss files in one another

2017-02-19 21:08 UTC, hubudibu commented on web/src/main.js
> +require('./css/_popup.scss');
if you `@import` the popup and dashboard css files in main.scss, you won't need to require them here again

2017-02-20 12:45 UTC, h-attila commented on web/src/css/main.scss
> +@external _popup.scss;
fixed

2017-02-20 12:45 UTC, h-attila commented on web/src/main.js
> +require('./css/_popup.scss');
fixed

2017-02-20 12:53 UTC, h-attila commented on web/src/main.js
> +require('./css/_popup.scss');
if I use @inport instead of require, site crashes (it starts without any css)
I think it can be a webpack settings problem.
So I use require.

2017-02-21 14:36 UTC, merged