design bugs fixed
greenfox-zerda-lasers/konnekt-frontend pull request #7
Opened 2017-01-30 22:21 UTC by h-attila

'lepj be' nagybetuvel
input mezonek ne legyen bordere, legyen 1px inset shadowja felul
input bal paddingja 13px
gombon ne legyen box-shadow
legyen vertikalisan kozepen a tartalom
ne logjon ki a feher a hatter alol semmilyen keparanyon

2017-01-31 10:39 UTC, hubudibu requested changes
+ remove box-shadow from button

2017-01-31 10:39 UTC, hubudibu commented on web/src/app.js
> +  $scope.header = 'LÉPJ BE';
leave text in sentence case, convert to UPPERCASE via CSS

2017-01-31 11:58 UTC, h-attila commented on web/src/app.js
> +  $scope.header = 'LÉPJ BE';
ok

2017-01-31 12:17 UTC, h-attila commented
desigb bugs fixed #2 :)

2017-01-31 23:28 UTC, h-attila commented
conflicts resolved

2017-02-01 11:03 UTC, hubudibu requested changes

2017-02-01 11:03 UTC, hubudibu commented on web/index.html
> +    <div class="spacer"></div>
if you want to have space below the konnekt-logo, add some margin-bottom to it instead

2017-02-01 12:53 UTC, hubudibu approved these changes

2017-02-01 12:53 UTC, merged